### PR TITLE
Styles Added and new fonts included

### PR DESCRIPTION
**Pull request by Infinity-Intellect**

### CODE REVIEW

**Comment by MD-AZMAL** [comment]
hey!.. good work but you have added only the regular fonts.... plz add all the variations of the fonts present

**Comment by MD-AZMAL** [comment]
i would suggest not updating the readme on the whole... you can simply add your font at the end of the list after adding all of its variants also plz avoid changing single quotes to double quotes as it will be hard for other people to contribute

**Comment by MD-AZMAL** [comment]
you  can have a clean fork and work over these

**Comment by Infinity-Intellect** [comment]
Sure thing, I'll work on it.

**Comment by MD-AZMAL** [comment]
ya sure ... work on it and then send another PR. Will close it for now.

**Pull request closed without merging**
